server:
  port: 8081

com.flow:

  exchangeprovider:
    type: "external"

  paging:
    defaultLimit: 13

spring:
  datasource:
    url: jdbc:h2:file:./db/demo
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true

  h2:
    console:
      enabled: true


